export const ADD_RECIPE_NEXT_STEP = 'ADD_RECIPE_NEXT_STEP';
export const ADD_RECIPE_PREVIOUS_STEP = 'ADD_RECIPE_PREVIOUS_STEP';
export const ADD_RECIPE_SET_INGREDIENTS = 'ADD_RECIPE_SET_INGREDIENTS';
export const ADD_RECIPE_TOGGLE_INGREDIENT = 'ADD_RECIPE_TOGGLE_INGREDIENT';
